### ISSUE TITLE
Logo design contribution 

### ISSUE THREAD

**Issue by maaudrana** [whataa/pandora#1]
Hallo @whataa 
I am a graphic designer.I am so exited about this and want to make a logo for this projects.If you have any requirements then let me know .its free for any open source projects.
Thank you

**Comment by maaudrana** [comment]
![pandora-01](https://user-images.githubusercontent.com/34313493/42132719-39c66f9e-7d3f-11e8-8984-54159f7e5fa0.jpg)

**Comment by whataa** [comment]
Very thanks. It looks good, but it's somewhat like a generic icon instead of logo, can you make it more integrated with this project? such as adding some elements like tools, android robot, box, etc, to emphasize that it is Android-related and for debugging. In addition, adding color may be more energetic.

**Comment by whataa** [comment]
Close because of no response
