### ISSUE TITLE
How to close it programmatically?

### ISSUE THREAD

**Issue by amanzan** [whataa/pandora#40]
I found it's possible to close with EntranceView.close().

However, my project will not compile trying to generate the release version, since EntranceView it's not part of the pandora-no-op.

Would it be possible to add it, even if close method is completely empty? I just want it to compile, I have pandora disabled for release mode.

Or is it a different way to hide the pandora bar?

**Comment by whataa** [comment]
This CLOSE API is not public since there is a corresponding action on the panel.  I am confused why you need to close it programmatically. And my idea is that the public APIs only includes the ones mentioned in the README, Otherwise, no-op will have to keep a lot of code for this.

Hope u avoid using EntranceView, If there is still a problem, please let me know.

**Comment by amanzan** [comment]
I have a menu and one of the options is to enable/disable pandora toolbar. That's why I wanted an option to disable it programmatically. I still think it could be quite useful for certain situations, but if you don't agree, it's not a big deal :) Thanks for the quick response!

**Comment by whataa** [comment]
OK, if you think it's useful, then it does be useful, I'll fix it later.

**Comment by whataa** [comment]
please check out v1.3.2

**Comment by amanzan** [comment]
Great, thanks a lot!
