### ISSUE TITLE
作者什么时候支持androidx啊

### ISSUE THREAD

**Issue by jiangyue2780** [whataa/pandora#44]

**Comment by whataa** [comment]
好的，请稍等几天，最近有点忙

**Comment by rafaco** [comment]
Hi Whataa, I've seen that you already migrated into AndroidX and I want you to reconsider it as you have considerably reduce the potencial audience for Pandora. 

Pandora was already compatible with apps using AndroidX via Jetifier, as well as apps using old support libraries. But now Pandora can only be included in apps migrated to AndroidX because apps including support libraries can't include libraries using AndroidX. 

There are tons of live legacy apps that can't easily upgrade to AndroidX or can't upgrade their Android Gradle Plugin to 3.2.0, which is required by AndroidX. I face the same problem recently and I end up downgrading my library from AndroidX back into support libraries in order to reach a largest audience.

If you decide to carry on with AndroidX, you should also update your readme with your new limitation: only for AndroidX migrated projects, so Android Gradle plugin >= 3.2.0 and Android Studio >= 3.2 are required.

By the way, awesome work with Pandora! Cheers!

**Comment by whataa** [comment]
Hi @rafaco , don't worry about that, I haven't publish it and I plan to publish 3.x for AndroidX and keep 2.x for the other. Both will remind updated. Anyway, thank you for your advice.

**Comment by whataa** [comment]
@jiangyue2780 @rafaco 

Due to jitPack, I finally decide to distinguish between the two versions by the `androidx_` prefix before the version number, for example: v2.0.2 , androidx_v.2.0.2

由于jitPack，无法通过版本号的大小来很好地区分两种版本，最终我采用了在版本号前面增加 ` androidx` 前缀来区别，例如：

android-support | androidX
--- | ---
v2.0.2 | androidx_v.2.0.2

**Comment by rafaco** [comment]
Hi @whataa, I like a lot your solution about having a secondary artifact for max compatibility without affecting the performance of the main artifact. Thanks for the idea!

Following your advice I'm going to generate 2 artifacts from my library: a short named one (_library_) for modern apps with AndroidX, and a postfixed one for older apps (_library-compat_). This allow me to downgrade even more the compat artifact without affecting the performance of the modern one (reaching my current goal of API 26 support libraries and Android Gradle Plugin 2.0.0). 

I'm only worried about maintainability as it will be tough using branches, do you have something in mind?  A module for each artifact sharing a core module seems the better options to me right now, but a single one with 2 variants could also work (using conditional dependencies and custom source sets for imports).

**Comment by whataa** [comment]
Thanks @rafaco , I would support the idea of sharing core module more. 

2 variants for Pandora is because the UIs have been stable, and it will not be changed in general. So it is not too much trouble to maintain. I only need to merge one branch to another. If your library's UIs change frequently, you may need to resolve conflicts or modify 'import' when you merge.
